#include "wdid.h"

/* 1. WDID MANUAL ENTRY */
static const char * const doc_wdid_lines[] = {
    "NAME",
    "  wdid - What Does It Do? Interactive manual page and documentation reader",
    "",
    "SYNOPSIS",
    "  wdid [command]",
    "",
    "DESCRIPTION",
    "  The wdid command is the built-in operating system manual reader. It works",
    "  very much like the traditional 'man' command in Linux and Unix systems.",
    "  When you want to understand what a specific command does, how its options",
    "  work, or how it communicates with system hardware, wdid provides an",
    "  in-depth, clear, and comprehensive manual page.",
    "",
    "  If you run wdid without any arguments, it opens this manual page, which",
    "  serves as the primary reference and index for the entire command suite.",
    "",
    "SCROLLING AND INTERACTIVE NAVIGATION",
    "  Because manual pages in dismasmOS contain rich and detailed technical",
    "  explanations, they are often much longer than a single 80x25 terminal screen.",
    "  The wdid pager provides interactive smooth scrolling with the following",
    "  input controls:",
    "",
    "  MOUSE SCROLL WHEEL:",
    "    Scroll Up   - Rolls the document up by 3 lines per notch.",
    "    Scroll Down - Rolls the document down by 3 lines per notch.",
    "",
    "  KEYBOARD PAGE NAVIGATION:",
    "    Page Up (PgUp)   - Jumps up by one full screen page (20 lines).",
    "    Page Down (PgDn) - Jumps down by one full screen page (20 lines).",
    "    Space Bar        - Advances forward by one full screen page.",
    "    'b' or 'B'       - Steps back by one full screen page.",
    "",
    "  KEYBOARD LINE NAVIGATION:",
    "    Up Arrow or 'k'   - Scrolls up by exactly 1 line.",
    "    Down Arrow or 'j' - Scrolls down by exactly 1 line.",
    "",
    "  DOCUMENT BOUNDARIES:",
    "    Home key or 'g'   - Jumps directly to the very first line (top).",
    "    End key or 'G'    - Jumps directly to the very last line (bottom).",
    "",
    "  EXITING THE MANUAL:",
    "    'q', 'Q', or ESC  - Exits the manual reader and restores the shell prompt.",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  The wdid viewer bypasses standard line scrolling and renders characters",
    "  directly into the dual-port VGA text buffer at physical address 0x000B8000.",
    "  The top 24 rows (0 through 23) display syntax-highlighted manual lines.",
    "  Row 24 is rendered in deep blue with white text, showing the active",
    "  document name, line counter range, total lines, and percentage read.",
    "",
    "  Mouse wheel events are handled by the bare-metal PS/2 auxiliary device",
    "  driver on IRQ 12. The kernel initializes the Intel 8042 controller into",
    "  IntelliMouse wheel mode using sample rates 200, 100, and 80. Whenever the",
    "  physical scroll wheel turns, the mouse sends 4-byte packets. The driver",
    "  extracts the Z-axis delta byte and feeds dedicated scroll codes into the",
    "  central input queue, waking the CPU from low-power halt.",
    "",
    "AVAILABLE DOCUMENTED COMMANDS IN DISMASMOS",
    "  You can view the full manual for any command by typing 'wdid <command>':",
    "    wdid help      - Displays summary list of all commands.",
    "    wdid clear     - Clears the 80x25 VGA video buffer.",
    "    wdid colr      - Displays the 16 VGA colors and 1-bit solid spots.",
    "    wdid heap      - Displays heap allocator status and runs self-test.",
    "    wdid calc      - Evaluates integer and hexadecimal math expressions.",
    "    wdid dump      - Dumps physical memory in hexadecimal and ASCII format.",
    "    wdid reg       - Displays all 64-bit CPU registers and control flags.",
    "    wdid asm       - Executes dynamic machine bytecode directly in RAM.",
    "    wdid lsf       - Lists filesystem directories with sizes and permissions.",
    "    wdid cd        - Changes the current working directory.",
    "    wdid makedir   - Creates new directories in the RAM filesystem.",
    "    wdid changes   - Displays filesystem access and modification audit logs.",
    "    wdid em        - Full-screen text editor with vocabulary validation.",
    "    wdid cat       - Prints the raw text contents of a file to the screen.",
    "    wdid echo      - Prints text or redirects output into files (>).",
    "    wdid touch     - Creates new empty files in the filesystem.",
    "    wdid rm        - Deletes files or directories from the filesystem.",
    "    wdid grep      - Searches for matching text patterns within files.",
    "    wdid pr        - Manages kernel background processes and comments.",
    "    wdid uname     - Displays operating system and kernel release info.",
    "    wdid MemRep    - Displays full system memory allocation map and stats.",
    "    wdid lang      - Switches keyboard layout between German and US.",
    "    wdid shutdown  - Shuts down agents and executes hardware power-off.",
    "    wdid reboot    - Pulses the CPU reset line for clean machine reboot.",
    "",
    "EXAMPLES",
    "  wdid",
    "    Opens the general manual overview and command index.",
    "",
    "  wdid heap",
    "    Opens the comprehensive manual page for the dynamic heap allocator.",
    "",
    "  wdid em",
    "    Opens the detailed manual page for the 'em' full-screen text editor.",
    "",
    "ERROR HANDLING",
    "  If you request a command name that does not exist (for example 'wdid xyz'),",
    "  the shell prints a notice in red text, plays a 3000 Hz acoustic error",
    "  tone on the PC speaker, and informs you to type 'wdid' for the index.",
    "",
    "SEE ALSO",
    "  help, uname, MemRep, em"
};

/* 2. HELP MANUAL ENTRY */
static const char * const doc_help_lines[] = {
    "NAME",
    "  help - Quick reference list of all available commands in dismasmOS",
    "",
    "SYNOPSIS",
    "  help",
    "",
    "DESCRIPTION",
    "  The help command prints a concise, single-line overview of every command",
    "  supported by the dismasmOS shell environment. While wdid is designed for",
    "  exhaustive reading with scrolling, help provides immediate reference",
    "  directly in the terminal buffer without clearing your screen.",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  When executed, help traverses the internal command registry and writes",
    "  each command's keyword and brief description string to the active VGA",
    "  cursor position using vga_puts(). The console scrolls upward naturally",
    "  if the output reaches the 25th row.",
    "",
    "COMMAND CATEGORIES",
    "  1. SYSTEM CONTROL & HARDWARE:",
    "     help, clear, colr, lang, uname, MemRep, shutdown, reboot, wdid.",
    "",
    "  2. FILESYSTEM & STORAGE:",
    "     lsf, cd, makedir, changes, cat, echo, touch, rm, grep, em.",
    "",
    "  3. DIAGNOSTICS & MEMORY:",
    "     heap, calc, dump, reg, asm, pr.",
    "",
    "PRACTICAL EXAMPLES",
    "  root@admin@dismasmOS:/home | >>> help",
    "    Prints all 24 available shell commands and their short descriptions.",
    "",
    "SEE ALSO",
    "  wdid, uname, MemRep"
};

/* 3. CLEAR MANUAL ENTRY */
static const char * const doc_clear_lines[] = {
    "NAME",
    "  clear - Clear the console screen buffer and reset hardware cursor",
    "",
    "SYNOPSIS",
    "  clear",
    "",
    "DESCRIPTION",
    "  The clear command wipes all characters and colors currently visible on the",
    "  VGA text screen, resetting the entire 80-column by 25-row matrix to blank",
    "  spaces with default light grey on black text attributes. It then moves the",
    "  hardware text cursor back to row 0, column 0 (the top-left corner).",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  In x86 video text mode, the display buffer is an array of 2000 16-bit words",
    "  starting at physical address 0x000B8000. Each word consists of an 8-bit",
    "  ASCII character code and an 8-bit attribute byte (foreground and background",
    "  colors).",
    "",
    "  The clear command performs the following sequence:",
    "  1. Iterates through all 2000 cells (80 columns * 25 rows).",
    "  2. Overwrites each cell with ASCII space (0x20) and the current attribute.",
    "  3. Sets internal kernel cursor variables (vga_row = 0, vga_col = 0).",
    "  4. Reprograms the hardware CRT Controller registers via I/O ports 0x3D4",
    "     and 0x3D5 to place the blinking hardware cursor at offset 0.",
    "",
    "PRACTICAL EXAMPLES",
    "  root@admin@dismasmOS:/home | >>> clear",
    "    Instantly resets the terminal screen to a clean slate.",
    "",
    "SEE ALSO",
    "  colr, wdid"
};

/* 4. COLR MANUAL ENTRY */
static const char * const doc_colr_lines[] = {
    "NAME",
    "  colr - Inspect 16 VGA palette colors or preview a 1-bit solid terminal spot",
    "",
    "SYNOPSIS",
    "  colr",
    "  colr <color_number>",
    "  colr <color_name>",
    "  colr (<color_name>)",
    "",
    "DESCRIPTION",
    "  The colr command manages the 16-color VGA text mode color palette. When run",
    "  without arguments, it outputs an interactive table listing all 16 standard",
    "  VGA colors (indices 0 through 15) alongside their names and a solid visual",
    "  spot block rendered in that exact shade.",
    "",
    "  When an argument is supplied, colr parses the color specification and",
    "  renders an immediate visual verification block (ASCII code 219 / 0xDB,",
    "  a 100% solid filled rectangular block) in that requested color.",
    "",
    "SUPPORTED ARGUMENTS & SYNTAX",
    "  1. NUMERIC INDICES (0-15):",
    "     colr 0  (black),        colr 1  (blue),         colr 2  (green),",
    "     colr 3  (cyan),         colr 4  (red),          colr 5  (magenta),",
    "     colr 6  (brown),        colr 7  (light grey),   colr 8  (dark grey),",
    "     colr 9  (light blue),   colr 10 (light green),  colr 11 (light cyan),",
    "     colr 12 (light red),    colr 13 (light magenta),colr 14 (yellow),",
    "     colr 15 (white).",
    "",
    "  2. ENGLISH COLOR NAMES:",
    "     red, blue, green, cyan, magenta, brown, yellow, white, light_blue,",
    "     light_green, light_cyan, light_red, light_magenta, dark_grey, light_grey.",
    "",
    "  3. GERMAN COLOR NAMES:",
    "     rot, blau, gruen (or grün), tuerkis (or türkis), lila, braun, gelb,",
    "     weiss (or weiß), hellblau, hellgruen (or hellgrün), helltuerkis,",
    "     hellrot, rosa, dunkelgrau, hellgrau.",
    "",
    "  4. BRACKETED SYNTAX:",
    "     Parentheses, brackets, or angle brackets are cleanly stripped by the",
    "     parser. For example, 'colr (blue)' or 'colr [rot]' are valid.",
    "",
    "ERROR HANDLING",
    "  If an invalid color string or out-of-bounds number is supplied, colr",
    "  reports an error, sounds a 1 ms 3000 Hz PC speaker error beep, and",
    "  suggests running 'colr' without arguments to see the available list.",
    "",
    "SEE ALSO",
    "  clear, wdid"
};

/* 5. LANG MANUAL ENTRY */
static const char * const doc_lang_lines[] = {
    "NAME",
    "  lang - Query or switch active keyboard layout (German QWERTZ / US QWERTY)",
    "",
    "SYNOPSIS",
    "  lang",
    "  lang <de|en>",
    "",
    "DESCRIPTION",
    "  The lang command controls the keyboard layout translation engine in the",
    "  PS/2 keyboard driver. dismasmOS supports two international layouts:",
    "    - de : German DIN 2137-2 (QWERTZ) with full AltGr decoding (Default)",
    "    - en : US Standard (QWERTY)",
    "",
    "  Running lang without arguments prints the currently active layout and usage.",
    "",
    "KEYBOARD MAPPING ARCHITECTURE",
    "  The keyboard driver reads hardware scancodes from port 0x60 upon IRQ 1.",
    "  The kernel maps these raw Set 1 scancodes into ASCII and special control",
    "  codes using ISO C99 designated initializers.",
    "",
    "  In German mode (de):",
    "    - 'Z' and 'Y' keys are in German QWERTZ positions.",
    "    - Umlauts (ä, ö, ü, Ä, Ö, Ü) and sharp s (ß) are fully supported.",
    "    - AltGr key (Right Alt, scancode 0xE0 0x38) unlocks third-level characters:",
    "      AltGr + Q = @,   AltGr + 7 = {,   AltGr + 8 = [,",
    "      AltGr + 9 = ],   AltGr + 0 = },   AltGr + ß = \\,",
    "      AltGr + + = ~,   AltGr + M = µ,   AltGr + < = |.",
    "",
    "  In US mode (en):",
    "    - Standard US QWERTY layout with symbols (@ above 2, # above 3, etc.).",
    "",
    "PRACTICAL EXAMPLES",
    "  lang",
    "    Prints 'current layout: de (German QWERTZ)'.",
    "",
    "  lang en",
    "    Switches the active layout to US QWERTY.",
    "",
    "  lang de",
    "    Switches the active layout to German QWERTZ.",
    "",
    "SEE ALSO",
    "  wdid, em"
};

/* 6. UNAME MANUAL ENTRY */
static const char * const doc_uname_lines[] = {
    "NAME",
    "  uname - Display operating system name, architecture, and dedication",
    "",
    "SYNOPSIS",
    "  uname",
    "",
    "DESCRIPTION",
    "  The uname command outputs core operating system metadata, confirming the",
    "  microkernel architecture, privilege level, and operational environment.",
    "",
    "OUTPUT BREAKDOWN",
    "  When executed, uname prints:",
    "    dismasmOS 1.4 (x86_64 Long Mode 64-Bit)",
    "    Creation of the Saviour",
    "    May God lead this Creation",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  The kernel runs strictly at CPU Privilege Level 0 (Ring 0) in 64-bit Long",
    "  Mode with 4-level paging enabled (PML4, PDPT, Page Directory). The CPU operates",
    "  with 2 MiB huge identity-mapped pages across the first 1 GiB of physical",
    "  RAM without userland Ring 3 isolation layers, maximizing raw speed and",
    "  deterministic bare-metal execution.",
    "",
    "SEE ALSO",
    "  MemRep, wdid"
};

/* 7. MEMREP MANUAL ENTRY */
static const char * const doc_memrep_lines[] = {
    "NAME",
    "  MemRep - Detailed memory allocation report and topology diagnostic",
    "",
    "SYNOPSIS",
    "  MemRep",
    "  memrep",
    "",
    "DESCRIPTION",
    "  MemRep (Memory Report) performs an exhaustive scan of the physical memory",
    "  layout, displaying the exact boundary addresses, sizes, attributes, and live",
    "  usage statistics of all subsystems in the 64-bit x86_64 address space.",
    "",
    "REPORTED REGIONS",
    "  MemRep outlines the following regions:",
    "    0x00000000 - 0x0007FFFF : Low Memory (512 KiB) - IVT, BDA, Boot Stack",
    "    0x00080000 - 0x0009FFFF : EBDA / BIOS (128 KiB) - Hardware Firmware",
    "    0x000A0000 - 0x000BFFFF : VGA VRAM (128 KiB) - MMIO Text Mode (0xB8000)",
    "    0x000C0000 - 0x000FFFFF : Firmware ROM (256 KiB) - System BIOS Code",
    "    Kernel .text            : Executable 64-bit code segment",
    "    Kernel .rodata          : Read-only strings and static manual tables",
    "    Kernel .data            : Initialized global variables",
    "    Kernel .bss             : Zero-initialized page tables, stack, buffers",
    "    Kernel Heap             : Dynamic allocator pool (16 MiB @ 0x01000000)",
    "    Identity RAM            : First 1 GiB mapped via 2 MiB huge pages",
    "",
    "LIVE RUNTIME METRICS",
    "  At the bottom of the report, MemRep calculates live consumption:",
    "    - RAMFS Payload: Used KiB vs total capacity and active file count.",
    "    - Process Memory: Process control block allocation and process count.",
    "    - Kernel Heap: Live allocated bytes, free bytes, and allocation count.",
    "    - Kernel Footprint: Combined binary size of text, rodata, data, and bss.",
    "    - Total System Used: Aggregated memory utilization in KiB.",
    "",
    "SEE ALSO",
    "  heap, dump, reg, wdid"
};

/* 8. SHUTDOWN MANUAL ENTRY */
static const char * const doc_shutdown_lines[] = {
    "NAME",
    "  shutdown - Halt operating system agents and execute hardware power-off",
    "",
    "SYNOPSIS",
    "  shutdown",
    "",
    "DESCRIPTION",
    "  The shutdown command performs a clean operating system shutdown and initiates",
    "  hardware power-off. It flushes in-memory filesystem tables, terminates background",
    "  process agents, and executes hardware ACPI and hypervisor shutdown routines.",
    "",
    "SHUTDOWN SEQUENCE",
    "  1. Clears the screen and displays system shutdown banner.",
    "  2. Confirms flushing of filesystem buffers to persistent state.",
    "  3. Stops all background process agents and daemons.",
    "  4. Issues power-off signals to virtual machine / hypervisor ports:",
    "       - Port 0x604  <= 0x2000 (QEMU ACPI power-off)",
    "       - Port 0xB004 <= 0x2000 (Bochs ACPI power-off)",
    "       - Port 0x4004 <= 0x3400 (Cloud-Hypervisor ACPI power-off)",
    "       - Port 0xF4   <= 0x00   (QEMU debug exit)",
    "  5. In case of physical hardware without soft power switch, executes an",
    "     inline assembly halt loop (cli; hlt; jmp) ensuring the CPU stops",
    "     processing and can be safely switched off manually.",
    "",
    "SAFETY NOTE",
    "  Once executed, the system halts immediately. Unsaved editor buffers",
    "  must be saved with ';wsc' before issuing shutdown.",
    "",
    "SEE ALSO",
    "  reboot, wdid"
};

/* 9. REBOOT MANUAL ENTRY */
static const char * const doc_reboot_lines[] = {
    "NAME",
    "  reboot - Perform immediate hardware machine reset via 8042 controller",
    "",
    "SYNOPSIS",
    "  reboot",
    "",
    "DESCRIPTION",
    "  The reboot command initiates an immediate cold hardware restart of the",
    "  computer. It triggers the processor's physical RESET line by pulsing the",
    "  Intel 8042 PS/2 microcontroller.",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  1. Disables all maskable interrupts on the CPU using the 'cli' instruction.",
    "  2. Polls I/O port 0x64 (PS/2 Controller Status Register) until the input",
    "     buffer is empty (bit 1 is 0).",
    "  3. Sends byte 0xFE to I/O port 0x64.",
    "     In the standard PC/AT architecture, command 0xFE pulses line 0 of the",
    "     microcontroller output port low, which is physically wired to the CPU",
    "     system reset line.",
    "  4. If the hardware takes a few cycles to reset, enters a tight 'hlt' loop.",
    "",
    "SEE ALSO",
    "  shutdown, wdid"
};

const struct wdid_entry wdid_doc_wdid = {
    "wdid", "man", "Interactive manual page and documentation reader",
    doc_wdid_lines, sizeof(doc_wdid_lines) / sizeof(doc_wdid_lines[0])
};

const struct wdid_entry wdid_doc_help = {
    "help", NULL, "Quick reference list of all available commands",
    doc_help_lines, sizeof(doc_help_lines) / sizeof(doc_help_lines[0])
};

const struct wdid_entry wdid_doc_clear = {
    "clear", "cls", "Clear the console screen buffer and reset cursor",
    doc_clear_lines, sizeof(doc_clear_lines) / sizeof(doc_clear_lines[0])
};

const struct wdid_entry wdid_doc_colr = {
    "colr", "color", "Inspect 16 VGA palette colors or preview 1-bit solid spot",
    doc_colr_lines, sizeof(doc_colr_lines) / sizeof(doc_colr_lines[0])
};

const struct wdid_entry wdid_doc_lang = {
    "lang", "keyboard", "Query or switch active keyboard layout (de/en)",
    doc_lang_lines, sizeof(doc_lang_lines) / sizeof(doc_lang_lines[0])
};

const struct wdid_entry wdid_doc_uname = {
    "uname", NULL, "Display operating system name, architecture, and dedication",
    doc_uname_lines, sizeof(doc_uname_lines) / sizeof(doc_uname_lines[0])
};

const struct wdid_entry wdid_doc_memrep = {
    "MemRep", "memrep", "Detailed memory allocation report and topology diagnostic",
    doc_memrep_lines, sizeof(doc_memrep_lines) / sizeof(doc_memrep_lines[0])
};

const struct wdid_entry wdid_doc_shutdown = {
    "shutdown", "poweroff", "Halt operating system agents and execute hardware power-off",
    doc_shutdown_lines, sizeof(doc_shutdown_lines) / sizeof(doc_shutdown_lines[0])
};

const struct wdid_entry wdid_doc_reboot = {
    "reboot", "restart", "Perform immediate hardware machine reset via 8042 controller",
    doc_reboot_lines, sizeof(doc_reboot_lines) / sizeof(doc_reboot_lines[0])
};
