#include "wdid.h"

/* 1. HEAP MANUAL ENTRY */
static const char * const doc_heap_lines[] = {
    "NAME",
    "  heap - Kernel dynamic heap memory allocator diagnostics and self-test",
    "",
    "SYNOPSIS",
    "  heap",
    "  heap test",
    "",
    "DESCRIPTION",
    "  The heap command inspects and validates the kernel's freestanding dynamic",
    "  memory allocator. In dismasmOS, there is no C standard library; all dynamic",
    "  memory (malloc, free, calloc, realloc) is managed by an independent, bare-metal",
    "  allocator implemented from scratch.",
    "",
    "  Running 'heap' without arguments prints live allocation statistics.",
    "  Running 'heap test' executes an automated validation suite that stresses all",
    "  core allocator routines.",
    "",
    "ALLOCATOR ARCHITECTURE & SPECIFICATIONS",
    "  - Memory Pool Location: Dedicated 16 MiB pool starting at physical address",
    "    0x01000000 (16 MiB boundary) up to 0x01FFFFFF (32 MiB boundary).",
    "  - 16-Byte Alignment: All memory payloads returned by malloc are strictly",
    "    aligned to 16-byte boundaries, satisfying x86_64 SSE/AVX requirements.",
    "  - 48-Byte Header Structure: Each allocated or free chunk contains:",
    "      * Magic Signature (0xDEADBEEFCAFE0001): Detects heap corruption.",
    "      * Size Field: 64-bit length of usable payload.",
    "      * Allocated Flag: Distinguishes live allocations from free blocks.",
    "      * Bidirectional Pointers: 64-bit prev and next pointers.",
    "  - Bidirectional Coalescing: When a chunk is freed, it is immediately merged",
    "    with adjacent free chunks to completely eliminate external fragmentation.",
    "  - Double-Free Detection: Guard checks abort and prevent double-free bugs.",
    "",
    "OPTIONS & MODES",
    "  heap",
    "    Displays total heap size (16 MiB), currently used bytes, remaining free",
    "    KiB, number of active allocations, and starting/ending addresses.",
    "",
    "  heap test",
    "    Runs an automated 4-stage diagnostic suite:",
    "      1. malloc test: Allocates varying chunk sizes and verifies alignment.",
    "      2. calloc test: Verifies all allocated bytes are zero-initialized.",
    "      3. realloc test: Expands and shrinks buffers, verifying data preservation.",
    "      4. free & coalesce test: Frees buffers in interleaved order and validates",
    "         that total free memory matches the original unfragmented state.",
    "",
    "PRACTICAL EXAMPLES",
    "  heap",
    "    Inspects current memory heap metrics.",
    "",
    "  heap test",
    "    Executes self-test. Prints '[  OK  ] All heap allocator tests passed!'",
    "",
    "SEE ALSO",
    "  MemRep, dump, wdid"
};

/* 2. CALC MANUAL ENTRY */
static const char * const doc_calc_lines[] = {
    "NAME",
    "  calc - Integer and hexadecimal arithmetic mathematical calculator",
    "",
    "SYNOPSIS",
    "  calc <expression>",
    "",
    "DESCRIPTION",
    "  The calc command evaluates mathematical expressions containing integer",
    "  arithmetic. It uses an internal recursive-descent parser supporting standard",
    "  algebraic operator precedence, nested parentheses, unary signs, and both",
    "  decimal and hexadecimal numbers.",
    "",
    "SUPPORTED OPERATORS & PRECEDENCE",
    "  1. Parentheses: ( ... ) - Overrides default precedence.",
    "  2. Unary Signs: + and - (e.g., -42, +10).",
    "  3. Multiplicative: * (multiplication), / (integer division), % (modulo).",
    "  4. Additive: + (addition), - (subtraction).",
    "",
    "NUMBER FORMATS",
    "  - Decimal: Standard base-10 digits (e.g. 100, 4096, 65535).",
    "  - Hexadecimal: Prefixed with '0x' or '0X' (e.g. 0x10, 0xB8000, 0x1000).",
    "",
    "OUTPUT FORMAT",
    "  The calculated result is printed simultaneously in two formats:",
    "    Result: <decimal_value> (<hexadecimal_value>)",
    "",
    "ERROR HANDLING",
    "  - Division by zero ('calc 10 / 0') prints an error and sounds the 3000 Hz",
    "    PC speaker warning tone.",
    "  - Syntax errors such as unbalanced parentheses ('calc (5 + 2') or unknown",
    "    characters sound the warning tone and print a syntax error message.",
    "",
    "PRACTICAL EXAMPLES",
    "  calc 10 + 5 * 2",
    "    Outputs: Result: 20 (0x00000014)",
    "",
    "  calc (10 + 5) * 2",
    "    Outputs: Result: 30 (0x0000001E)",
    "",
    "  calc 0x1000 + 0x200",
    "    Outputs: Result: 4608 (0x00001200)",
    "",
    "SEE ALSO",
    "  dump, reg, wdid"
};

/* 3. DUMP MANUAL ENTRY */
static const char * const doc_dump_lines[] = {
    "NAME",
    "  dump - Formatted hexadecimal and ASCII memory inspection utility",
    "",
    "SYNOPSIS",
    "  dump <address> [length]",
    "",
    "DESCRIPTION",
    "  The dump command reads raw physical or virtual memory bytes directly from",
    "  the 64-bit kernel space and prints a formatted memory dump to the console.",
    "  Each line displays the 64-bit starting address, sixteen hexadecimal bytes",
    "  with a center dividing spacer, and an ASCII pane on the right showing",
    "  printable text.",
    "",
    "ARGUMENTS",
    "  address",
    "    The target 64-bit memory address. Can be specified in hexadecimal (e.g.",
    "    0xB8000, 0x100000) or decimal format.",
    "",
    "  length (Optional)",
    "    Number of bytes to dump. If omitted, defaults to 64 bytes. For safety,",
    "    the length is capped at a maximum of 512 bytes per command invocation.",
    "",
    "DISPLAY PANE FORMAT",
    "  0x00000000000B8000: 57 0F 65 0F 6C 0F 63 0F  6F 0F 6D 0F 65 0F 20 0F |W.e.l.c.o.m.e. .|",
    "  - Left: 64-bit base offset.",
    "  - Middle: 16 hex byte columns with a spacer between byte 7 and 8.",
    "  - Right: ASCII representation. Printable characters (ASCII 32-126) are shown",
    "    directly; non-printable bytes are represented as dots ('.').",
    "",
    "PRACTICAL EXAMPLES",
    "  dump 0xB8000 32",
    "    Dumps the first 32 bytes of the active VGA video text buffer.",
    "",
    "  dump 0x100000 64",
    "    Inspects the kernel 64-bit entry point and early machine instructions.",
    "",
    "SEE ALSO",
    "  reg, asm, MemRep, wdid"
};

/* 4. REG MANUAL ENTRY */
static const char * const doc_reg_lines[] = {
    "NAME",
    "  reg - Display CPU 64-bit general-purpose, control, and flag registers",
    "",
    "SYNOPSIS",
    "  reg",
    "",
    "DESCRIPTION",
    "  The reg command captures the current hardware CPU register context directly",
    "  from the running 64-bit processor core using inline assembly, presenting a",
    "  live diagnostic snapshot of all primary processor state registers.",
    "",
    "CAPTURED REGISTERS",
    "  1. 64-BIT GENERAL PURPOSE REGISTERS:",
    "     - RAX, RBX, RCX, RDX : Standard arithmetic, counter, and data registers.",
    "     - RSI, RDI           : Source and destination index registers.",
    "     - RBP, RSP           : Base pointer and active stack pointer.",
    "     - R8 through R15     : Extended x86_64 64-bit registers.",
    "",
    "  2. CONTROL REGISTERS:",
    "     - CR0 : Protection Enable (PE), Paging (PG), Task Switched (TS).",
    "     - CR2 : Page Fault Linear Address (address that caused a fault).",
    "     - CR3 : Page Directory Base Register (points to the PML4 page table).",
    "     - CR4 : Operating mode extensions (PAE enabled, OSFXSR).",
    "",
    "  3. RFLAGS REGISTER & STATUS FLAGS:",
    "     - Unpacks and displays live CPU arithmetic and system flags:",
    "       * CF : Carry Flag",
    "       * ZF : Zero Flag",
    "       * SF : Sign Flag",
    "       * IF : Interrupt Enable Flag (must be 1 for keyboard/mouse to work)",
    "       * DF : Direction Flag",
    "       * OF : Overflow Flag",
    "",
    "PRACTICAL EXAMPLES",
    "  reg",
    "    Displays complete register diagnostic table.",
    "",
    "SEE ALSO",
    "  asm, dump, MemRep, wdid"
};

/* 5. ASM MANUAL ENTRY */
static const char * const doc_asm_lines[] = {
    "NAME",
    "  asm - Execute dynamic machine code or x86 processor instructions in RAM",
    "",
    "SYNOPSIS",
    "  asm <mnemonic>",
    "  asm <bytecode_hex>",
    "",
    "DESCRIPTION",
    "  The asm command provides an interactive runtime environment for executing",
    "  raw x86_64 machine code instructions directly in memory. It can execute",
    "  hardware processor mnemonics or arbitrary hex byte sequences in Ring 0.",
    "",
    "HOW IT WORKS UNDER THE HOOD",
    "  When hex bytecode is provided:",
    "  1. The kernel parses the input hex tokens into an executable memory buffer.",
    "  2. Validates that the sequence terminates with a return instruction (0xC3).",
    "     If missing, the kernel automatically appends 0xC3.",
    "  3. Casts the buffer address to a 64-bit C function pointer:",
    "     typedef uint64_t (*asm_func_t)(void);",
    "  4. Calls the buffer directly as executable 64-bit code.",
    "  5. Captures the RAX register returned by the function and displays it in",
    "     both hexadecimal and decimal format.",
    "",
    "BUILT-IN MNEMONICS",
    "  asm nop",
    "    Executes a single hardware No-Operation instruction (0x90).",
    "",
    "  asm cli",
    "    Disables all maskable hardware interrupts on the CPU (clears RFLAGS.IF).",
    "",
    "  asm sti",
    "    Enables maskable hardware interrupts on the CPU (sets RFLAGS.IF).",
    "",
    "  asm rdtsc",
    "    Executes the Read Time-Stamp Counter instruction. Reads the CPU clock",
    "    cycles since processor reset into EDX:EAX and displays the 64-bit tick count.",
    "",
    "  asm cpuid",
    "    Executes CPUID with EAX=0. Extracts the 12-byte processor vendor string",
    "    from EBX, EDX, and ECX (e.g. 'GenuineIntel' or 'AuthenticAMD').",
    "",
    "RAW BYTECODE EXAMPLES",
    "  asm 48 c7 c0 2a 00 00 00 c3",
    "    Executes 'mov rax, 42; ret'. Prints Return RAX: 0x0000002A (42).",
    "",
    "SAFETY WARNING",
    "  Because bytecode executes with Ring 0 supervisor privileges, executing",
    "  invalid instructions or jumping into unmapped addresses will cause a CPU fault.",
    "",
    "SEE ALSO",
    "  reg, dump, wdid"
};

/* 6. PR MANUAL ENTRY */
static const char * const doc_pr_lines[] = {
    "NAME",
    "  pr - Kernel process subsystem manager, status inspector, and daemon control",
    "",
    "SYNOPSIS",
    "  pr",
    "  pr status [process_name]",
    "  pr start <process_name>",
    "  pr kill <process_name>",
    "  pr -c <comment> <process_name>",
    "",
    "DESCRIPTION",
    "  The pr command interfaces with the dismasmOS process subsystem. It enables",
    "  inspecting active kernel processes, launching background tasks, terminating",
    "  daemons, and attaching administrative comments to process control blocks.",
    "",
    "SUBCOMMANDS & MODES",
    "  pr",
    "    Lists all registered processes, showing PID, name, state (RUNNING,",
    "    STOPPED), memory consumption in KiB, and comment annotations.",
    "",
    "  pr status <process_name>",
    "    Displays detailed runtime metrics for a single designated process.",
    "",
    "  pr start <process_name>",
    "    Initializes and starts a new process instance or resumes an existing one.",
    "",
    "  pr kill <process_name>",
    "    Signals and halts an active process daemon.",
    "",
    "  pr -c <comment> <process_name>",
    "    Attaches an administrative comment string (up to 64 characters) to the",
    "    process control block for audit and diagnostic tracking.",
    "",
    "SYSTEM PROCESSES",
    "  - service.prf : Default system agent process initialized at kernel boot.",
    "",
    "PRACTICAL EXAMPLES",
    "  pr",
    "    Prints process status table.",
    "",
    "  pr -c \"Primary networking daemon\" service.prf",
    "    Attaches an administrative description to service.prf.",
    "",
    "SEE ALSO",
    "  MemRep, changes, wdid"
};

const struct wdid_entry wdid_doc_heap = {
    "heap", "malloc", "Kernel dynamic heap memory allocator diagnostics & self-test",
    doc_heap_lines, sizeof(doc_heap_lines) / sizeof(doc_heap_lines[0])
};

const struct wdid_entry wdid_doc_calc = {
    "calc", "math", "Integer and hexadecimal arithmetic mathematical calculator",
    doc_calc_lines, sizeof(doc_calc_lines) / sizeof(doc_calc_lines[0])
};

const struct wdid_entry wdid_doc_dump = {
    "dump", "hexdump", "Formatted hexadecimal and ASCII memory inspection utility",
    doc_dump_lines, sizeof(doc_dump_lines) / sizeof(doc_dump_lines[0])
};

const struct wdid_entry wdid_doc_reg = {
    "reg", "registers", "Display CPU 64-bit general-purpose, control, and flag registers",
    doc_reg_lines, sizeof(doc_reg_lines) / sizeof(doc_reg_lines[0])
};

const struct wdid_entry wdid_doc_asm = {
    "asm", "bytecode", "Execute dynamic machine code or x86 processor instructions in RAM",
    doc_asm_lines, sizeof(doc_asm_lines) / sizeof(doc_asm_lines[0])
};

const struct wdid_entry wdid_doc_pr = {
    "pr", "ps", "Kernel process subsystem manager and daemon control",
    doc_pr_lines, sizeof(doc_pr_lines) / sizeof(doc_pr_lines[0])
};
